---
- name: Conf dynamicWeb server
  hosts: DynamicWeb # имя хоста, который мы создадим Vagrant`om
  become: yes # Установка Docker через sudo
  gather_facts: false
  tasks: # Перечисляем задачи которые выполнит наш playbook
  - name: Install docker packages # устанавливаем пакеты необходимые для установки докера
    become: yes
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
      - docker

  - name: Add Docker s official GPG key # добавляем GPG ключи для Docker
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker

  - name: Verify that we have the key with the fingerprint # проверяем наличие ключа с "отпечатком пальца"
    become: yes    
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker

  - name: Set up the stable repository # добавляем репозиторий докера
    become: yes    
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
      - docker
  
  - name: Update apt packages # обновление базы данных пакетного менеджера
    become: yes    
    apt:
      update_cache: yes
    tags:
      - docker

  - name: Install docker # установка docker
    become: yes    
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    tags:
      - docker

  - name: Add remote "vagrant" user to "docker" group # добавляем пользователя vagrant к группе безопасности docker
    become: yes
    user:
      name: vagrant
      group: "docker"
      append: yes
    tags:
      - docker 
  
  - name: Install docker-compose # установка docker-compose
    become: yes
    get_url:
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0777
      
  - name: Copy project # Копируем проект с хост машины в созданную через vagrant
    copy: src=project dest=/home/vagrant
  - name: reset ssh connection # чтобы применились права на использование docker, необходимо перелогиниться
    meta: reset_connection
  - name: Run container # производим развертывание необходимых контейнеров через docker-compose.yml
    shell:
      cmd: "docker-compose -f docker-compose.yml up -d"
      chdir: /home/vagrant/project

